blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/republic-chain/republic/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: 📖 Documentation
    url: https://github.com/republic-chain/republic/blob/master/README.md
    about: Read the project documentation and technical specifications
  - name: 🔒 Security Issues
    url: mailto:security@republic-chain.org
    about: Please report security vulnerabilities privately via email